2024-11-07 00:01:04,650 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\pythonProjectsForUniversity\Module_12_testing\test_12_4.py", line 41, in test_run
    run_run = rt_with_exceptions.Runner(10, 10)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProjectsForUniversity\Module_12_testing\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-07 00:01:04,651 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\pythonProjectsForUniversity\Module_12_testing\test_12_4.py", line 26, in test_wolk
    run_wolk = rt_with_exceptions.Runner('Wolk', -5)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProjectsForUniversity\Module_12_testing\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
